[book]
authors = ["SebaPascal"]
language = "en"
multilingual = false
src = "src"
title = "Process and Safety"

[preprocessor.plantuml]
plantuml-cmd="http://localhost:8080"

[output.html]
default-theme = "Rust"
